@echo off
echo Installing Python dependencies...
pip install -r requirements.txt

echo Installing Node.js dependencies...
call npm install

echo Building the React app...
call npm run build

echo Starting the Python server...
python server.py 